[package]
name = "asd"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { git = "https://github.com/shafai-pouya/ratatui", branch = "feat/custom-underlines" }
crossterm = "0.29.0"
color-eyre = "0.6.5"
chrono = "0.4.44"
libc = "0.2.186"
unicode-segmentation = "1.13.2"
emojis = "0.9.0"
once_cell = "1.21.4"